# Generated by Django 5.2.7 on 2025-10-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_almacen', models.SmallIntegerField()),
                ('tipo_almacen', models.CharField(choices=[('material', 'Material'), ('archivos', 'Archivos')], max_length=8)),
                ('ubicacion', models.TextField()),
                ('estado_almacen', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=8)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
                'constraints': [models.UniqueConstraint(fields=('nro_almacen', 'tipo_almacen'), name='unique_nro_almacen_tipo_almacen')],
            },
        ),
    ]
